version: "3"
services:
  mongodb:
    container_name: mongodb_interview
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

